export const OPERAND_ADDED = 'OPERAND_ADDED';
export const OPERAND_SUBTRACTED = 'OPERAND_SUBTRACTED';
export const OPERAND_MULTIPLIED = 'OPERAND_MULTIPLIED';
export const OPERAND_DIVIDED = 'OPERAND_DIVIDED';
export const DIGIT_TO_OPERAND_ADDED = 'NUMBER_TO_OPERAND_ADDED';
